# Generated by Django 4.1.2 on 2022-10-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonVi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MaSoThue", models.CharField(max_length=14)),
                ("TenDonVi", models.CharField(max_length=255)),
                ("DiaChi", models.CharField(max_length=255)),
                ("SoDienThoai", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="HoaDonDienTu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MaSoThue", models.CharField(max_length=14)),
                ("KyHieu", models.CharField(max_length=255)),
                ("So", models.CharField(max_length=255)),
                ("NgayHoaDon", models.DateField()),
                ("SoTien", models.BigIntegerField()),
                ("DiaChiTraCuu", models.CharField(max_length=255)),
                ("MaSoBiMat", models.CharField(max_length=255)),
                ("NguoiThanhToan", models.CharField(max_length=255)),
                ("NgayNhap", models.DateField()),
                ("DaThanhToan", models.BooleanField()),
                ("NgayThanhToan", models.DateField()),
            ],
        ),
    ]
